#!/bin/sh
 
### BEGIN INIT INFO
# Provides: pisurv
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Raspberry Pi surveillance
# Description: Raspberry Pi surveillance
### END INIT INFO
 
# Change the next 3 lines to suit where you install your script and what you want to call it
DIR=INSTALL_DIRECTORY
DAEMON_REC=$DIR/recorder.py
DAEMON_WEB=$DIR/webview.py
DAEMON_NAME=pisurv
 
# This next line determines what user the script runs as.
# Root generally not recommended but necessary if you are using the Raspberry Pi GPIO from Python.
DAEMON_USER=root
 
# The process ID of the script when it runs is stored here:
PIDFILE_REC=/var/run/pisurv_rec.pid
PIDFILE_WEB=/var/run/pisurv_web.pid
 
. /lib/lsb/init-functions
 
do_start () {
log_daemon_msg "Starting system $DAEMON_NAME daemon"
start-stop-daemon --start --background --pidfile $PIDFILE_REC --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --chdir $DIR --startas $DAEMON_REC
start-stop-daemon --start --background --pidfile $PIDFILE_WEB --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --chdir $DIR --startas $DAEMON_WEB
log_end_msg $?
}
do_stop () {
log_daemon_msg "Stopping system $DAEMON_NAME daemon"
start-stop-daemon --stop --pidfile $PIDFILE_REC --retry 10
start-stop-daemon --stop --pidfile $PIDFILE_WEB --retry 10
log_end_msg $?
}
 
case "$1" in
 
start|stop)
do_${1}
;;
 
restart|reload|force-reload)
do_stop
do_start
;;
 
status)
status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
;;
*)
echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
exit 1
;;
 
esac
exit 0
